export enum ProductErrorCode {
    PRODUCT_NAME_INPUT_ERROR = 'PRODUCT_NAME_INPUT_ERROR',
    PRODUCT_DESC_INPUT_ERROR = 'PRODUCT_DESC_INPUT_ERROR',
    PRODUCT_PRICE_INPUT_ERROR = 'PRODUCT_PRICE_INPUT_ERROR',
    PRODUCT_PRICE_INPUT_ERROR2 = 'PRODUCT_PRICE_INPUT_ERROR2',
    PRODUCT_EXPIRY_INPUT_ERROR1 = 'PRODUCT_EXPIRY_INPUT_ERROR1',
    PRODUCT_EXPIRY_INPUT_ERROR2 = 'PRODUCT_EXPIRY_INPUT_ERROR2',
    PRODUCT_LENGTH_INPUT_ERROR1 = 'PRODUCT_LENGTH_INPUT_ERROR1',
    PRODUCT_LENGTH_INPUT_ERROR2 = 'PRODUCT_LENGTH_INPUT_ERROR2',
    PRODUCT_HEIGHT_INPUT_ERROR1 = 'PRODUCT_HEIGHT_INPUT_ERROR1',
    PRODUCT_HEIGHT_INPUT_ERROR2 = 'PRODUCT_HEIGHT_INPUT_ERROR2',
    PRODUCT_WIDTH_INPUT_ERROR1 = 'PRODUCT_WIDTH_INPUT_ERROR1',
    PRODUCT_WIDTH_INPUT_ERROR2 = 'PRODUCT_WIDTH_INPUT_ERROR2',
    PRODUCT_WEIGHT_INPUT_ERROR1 = 'PRODUCT_WEIGHT_INPUT_ERROR1',
    PRODUCT_WEIGHT_INPUT_ERROR2 = 'PRODUCT_WEIGHT_INPUT_ERROR2',
    CATEGORY_REQUIRED_ERROR = 'CATEGORY_REQUIRED_ERROR',
    RECIPE_REQUIRED_ERROR = 'RECIPE_REQUIRED_ERROR',
    PRODUCT_NAME_LENGTH_ERROR = 'PRODUCT_NAME_LENGTH_ERROR',
    PRODUCT_DESC_LENGTH_ERROR = 'PRODUCT_DESC_LENGTH_ERROR',
    PRODUCT_EXPIRY_WARNING_ERROR= 'PRODUCT_EXPIRY_WARNING_ERROR',
    PRODUCT_EXPIRY_WARNING_ERROR1 = 'PRODUCT_EXPIRY_WARNING_ERROR1',
    PRODUCT_EXPIRY_WARNING_ERROR2 = 'PRODUCT_EXPIRY_WARNING_ERROR2',
    PRODUCT_DISCOUNT_LIMIT_ERROR = 'PRODUCT_DISCOUNT_LIMIT_ERROR',
    PRODUCT_IMAGE_REQUIRED_ERROR = 'PRODUCT_IMAGE_REQUIRED_ERROR',
    CONNECT_ERROR = 'CONNECT_ERROR',
    POST_PRODUCT_SUCCESS = 'POST_SUCCESS',
}
export const errorProductMessages: { [key in ProductErrorCode]: string } = {
    [ProductErrorCode.PRODUCT_NAME_INPUT_ERROR]: 'Vui lòng nhập tên sản phẩm',
    [ProductErrorCode.PRODUCT_DESC_INPUT_ERROR]: 'Vui lòng nhập mô tả sản phẩm',
    [ProductErrorCode.PRODUCT_PRICE_INPUT_ERROR]: 'Vui lòng nhập giá sản phẩm',
    [ProductErrorCode.PRODUCT_PRICE_INPUT_ERROR2]: 'Giá sản phẩm không được nhỏ hơn 1,000đ',
    [ProductErrorCode.PRODUCT_EXPIRY_INPUT_ERROR1]: 'Vui lòng nhập thời hạn sử dụng',
    [ProductErrorCode.PRODUCT_EXPIRY_INPUT_ERROR2]: 'Định dạng thời hạn sử dụng không hợp lệ',
    [ProductErrorCode.PRODUCT_LENGTH_INPUT_ERROR1]: 'Vui lòng nhập chiều dài sản phẩm',
    [ProductErrorCode.PRODUCT_LENGTH_INPUT_ERROR2]: 'Chiều dài sản phẩm phải từ 1cm đến 200cm',
    [ProductErrorCode.PRODUCT_HEIGHT_INPUT_ERROR1]: 'Vui lòng nhập chiều cao sản phẩm',
    [ProductErrorCode.PRODUCT_HEIGHT_INPUT_ERROR2]: 'Chiều cao sản phẩm phải từ 1cm đến 200cm',
    [ProductErrorCode.PRODUCT_WIDTH_INPUT_ERROR1]: 'Vui lòng nhập chiều rộng sản phẩm',
    [ProductErrorCode.PRODUCT_WIDTH_INPUT_ERROR2]: 'Chiều rộng sản phẩm phải từ 1cm đến 200cm',
    [ProductErrorCode.PRODUCT_WEIGHT_INPUT_ERROR1]: 'Vui lòng nhập khối lượng sản phẩm',
    [ProductErrorCode.PRODUCT_WEIGHT_INPUT_ERROR2]: 'Khối lượng sản phẩm phải từ 1g đến 20,000g',
    [ProductErrorCode.CATEGORY_REQUIRED_ERROR]: 'Vui lòng chọn danh mục',
    [ProductErrorCode.RECIPE_REQUIRED_ERROR]: 'Vui lòng chọn công thức',
    [ProductErrorCode.PRODUCT_NAME_LENGTH_ERROR]: 'Tên sản phẩm không được vượt quá 250 ký tự',
    [ProductErrorCode.PRODUCT_DESC_LENGTH_ERROR]: 'Mô tả không được vượt quá 500 ký tự',
    [ProductErrorCode.PRODUCT_EXPIRY_WARNING_ERROR]: 'Cảnh báo hạn sử dụng không được bỏ trống',
    [ProductErrorCode.PRODUCT_EXPIRY_WARNING_ERROR1]: 'Cảnh báo hạn sử dụng không được âm',
    [ProductErrorCode.PRODUCT_EXPIRY_WARNING_ERROR2]: 'Cảnh báo hạn sử dụng không được lớn hơn hạn sử dụng',
    [ProductErrorCode.PRODUCT_DISCOUNT_LIMIT_ERROR]: 'Giới hạn giảm giá phải từ 0 đến 100',
    [ProductErrorCode.PRODUCT_IMAGE_REQUIRED_ERROR]: 'Vui lòng chọn ít nhất một ảnh',
    [ProductErrorCode.CONNECT_ERROR	]: 'Có lỗi xảy ra khi lưu sản phẩm',
    [ProductErrorCode.POST_PRODUCT_SUCCESS	]: 'Lưu sản phẩm hành công'


};