export enum IngredientErrorCode {
    INGREDIENT_FETCH_FAIL = 'INGREDIENT_FETCH_FAIL',
    UNIT_FETCH_FAIL = 'UNIT_FETCH_FAIL',
    IMPORT_INGREDIENT_FETCH_FAIL = 'IMPORT_INGREDIENT_FETCH_FAIL',
    EXPORT_INGREDIENT_FETCH_FAIL = 'EXPORT_INGREDIENT_FETCH_FAIL',
    INGREDIENT_NAME_REQUIRED = 'INGREDIENT_NAME_REQUIRED',
    INGREDIENT_NAME_LENGTH = 'INGREDIENT_NAME_LENGTH',
    INGREDIENT_UNIT_REQUIRED = 'INGREDIENT_UNIT_REQUIRED',
    INGREDIENT_WARNING_LIMIT = 'INGREDIENT_WARNING_LIMIT',
    INGREDIENT_ADD_SUCCESS = 'INGREDIENT_ADD_SUCCESS',
    INGREDIENT_DELETE_SUCCESS = 'INGREDIENT_DELETE_SUCCESS',
    INGREDIENT_UPDATE_SUCCESS = 'INGREDIENT_UPDATE_SUCCESS',
    INGREDIENT_ADD_FAIL = 'INGREDIENT_ADD_FAIL',
    INGREDIENT_DELETE_FAIL = 'INGREDIENT_DELETE_FAIL',
    INGREDIENT_UPDATE_FAIL = 'INGREDIENT_UPDATE_FAIL',
    UNIT_NAME_REQUIRED = 'UNIT_NAME_REQUIRED',
    UNIT_NAME_LENGTH = 'UNIT_NAME_LENGTH',
    UNIT_ADD_SUCCESS = 'UNIT_ADD_SUCCESS',
    UNIT_ADD_FAIL = 'UNIT_ADD_FAIL',
    IMPORT_INGREDIENT_QUANTITY = 'IMPORT_INGREDIENT_QUANTITY',
    IMPORT_INGREDIENT_PRICE = 'IMPORT_INGREDIENT_PRICE',
    IMPORT_INGREDIENT_EMPTY = 'IMPORT_INGREDIENT_EMPTY',
    IMPORT_INGREDIENT_PRICE_EMPTY = 'IMPORT_INGREDIENT_PRICE_EMPTY',
    IMPORT_INGREDIENT_SUCCESS = 'IMPORT_INGREDIENT_SUCCESS',
    IMPORT_INGREDIENT_FAIL = 'IMPORT_INGREDIENT_FAIL',
    EXPORT_INGREDIENT_PRODUCT_EMPTY = 'EXPORT_INGREDIENT_PRODUCT_EMPTY',
    EXPORT_INGREDIENT_PRODUCT_QUANTITY = 'EXPORT_INGREDIENT_PRODUCT_QUANTITY',
    EXPORT_INGREDIENT_PRODUCT_QUANTITY_EMPTY = 'EXPORT_INGREDIENT_PRODUCT_QUANTITY_EMPTY',
    EXPORT_INGREDIENT_SUCCESS = 'EXPORT_INGREDIENT_SUCCESS',
    EXPORT_INGREDIENT_FAIL = 'EXPORT_INGREDIENT_FAIL',

    USER_FETCH_FAIL = 'USER_FETCH_FAIL',
    PRODUCT_FETCH_ERROR = 'PRODUCT_FETCH_ERROR',
}

export const ingredientErrorMessages: { [key in IngredientErrorCode]: string } = {
    [IngredientErrorCode.INGREDIENT_NAME_REQUIRED]: "Vui lòng nhập tên danh mục",
    [IngredientErrorCode.INGREDIENT_NAME_LENGTH]: "Tên nguyên liệu không được quá 100 ký tự",
    [IngredientErrorCode.INGREDIENT_UNIT_REQUIRED]: "Vui lòng chọn đơn vị cho nguyên liệu",
    [IngredientErrorCode.INGREDIENT_WARNING_LIMIT]: "Giới hạn cảnh báo không được nhỏ hơn 0",
    [IngredientErrorCode.INGREDIENT_ADD_SUCCESS]: "Thêm nguyên liệu thành công",
    [IngredientErrorCode.INGREDIENT_DELETE_SUCCESS]: "Xóa nguyên liệu thành công",
    [IngredientErrorCode.INGREDIENT_UPDATE_SUCCESS]: "Sửa nguyên liệu thành công",
    [IngredientErrorCode.INGREDIENT_ADD_FAIL]: "Thêm nguyên liệu mới thất bại",
    [IngredientErrorCode.INGREDIENT_DELETE_FAIL]: "Xóa nguyên liệu thất bại",
    [IngredientErrorCode.INGREDIENT_UPDATE_FAIL]: "Sửa nguyên liệu thất bại",
    [IngredientErrorCode.UNIT_NAME_REQUIRED]: "Tên đơn vị không được để trống",
    [IngredientErrorCode.UNIT_NAME_LENGTH]: "Tên đơn vị không được dài quá 50 ký tự",
    [IngredientErrorCode.UNIT_ADD_SUCCESS]: "Thêm đơn vị mới thành công",
    [IngredientErrorCode.UNIT_ADD_FAIL]: "Thêm đơn vị mới thất bại",
    [IngredientErrorCode.IMPORT_INGREDIENT_QUANTITY]: "Số lượng nguyên liệu nhập không được nhỏ hơn 1",
    [IngredientErrorCode.IMPORT_INGREDIENT_PRICE]: "Giá của nguyên liệu nhập không được nhỏ hơn 0",
    [IngredientErrorCode.IMPORT_INGREDIENT_EMPTY]: "Phải có ít nhất một nguyên liệu nhập",
    [IngredientErrorCode.IMPORT_INGREDIENT_PRICE_EMPTY]: "Giá nguyên liệu nhập không được bỏ trống",
    [IngredientErrorCode.IMPORT_INGREDIENT_SUCCESS]: "Nhập nguyên liệu thành công",
    [IngredientErrorCode.IMPORT_INGREDIENT_FAIL]: "Nhập nguyên liệu thất bại",
    [IngredientErrorCode.EXPORT_INGREDIENT_PRODUCT_EMPTY]: "Chưa chọn bánh cần làm để xuất nguyên liệu",
    [IngredientErrorCode.EXPORT_INGREDIENT_PRODUCT_QUANTITY]: "Số lượng bánh phải lớn hơn 0",
    [IngredientErrorCode.EXPORT_INGREDIENT_PRODUCT_QUANTITY_EMPTY]: "Vui lòng nhập số lượng bánh cần làm",
    [IngredientErrorCode.EXPORT_INGREDIENT_SUCCESS]: "Xuất nguyên liệu thành công",
    [IngredientErrorCode.EXPORT_INGREDIENT_FAIL]: "Xuất nguyên liệu thất bại",
    [IngredientErrorCode.INGREDIENT_FETCH_FAIL]: "Lấy danh sách nguyên liệu thất bại",
    [IngredientErrorCode.UNIT_FETCH_FAIL]: "Lấy danh sách đơn vị thất bại",
    [IngredientErrorCode.IMPORT_INGREDIENT_FETCH_FAIL]: "Lấy danh sách lịch sử nhập nguyên liệu thất bại",
    [IngredientErrorCode.EXPORT_INGREDIENT_FETCH_FAIL]: "Lấy danh sách lịch sử xuất nguyên liệu thất bại",

    [IngredientErrorCode.USER_FETCH_FAIL]: "Lấy danh sách người dùng thất bại",
    [IngredientErrorCode.PRODUCT_FETCH_ERROR]: "Lấy danh sách sản phẩm thất bại"
};